src/entity.js
src/request.js
system-test/datastore.js
test/entity.js

Fixes #13. PR ported from [this one](https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2773). In addition, adds an example to the documentation.

Support excludeFromIndexes for primitives in arrays.

---

src/request.js
test/request.js

Fixes #20 
When we switched to GAPIC, we inadvertently began returning `info.endCursor` as a Buffer. In the previous version (<=1.1), we returned the Buffer base64-stringified.

Return endCursor as a base64 string.

---

src/index.js
test/index.js

Fixes #23 
When a Datastore instance is created, we detect and pluck out the URL components of an emulator host via `determineBaseUrl_()`, then pass them to GAPIC, so that gRPC it can properly connect to the emulator. `determineBaseUrl_()` was making a mistake-- when it parsed out the `8081` port component, it cached it as a string instead of a number. Our constructor then tried to validate that a `port` existed by checking if it was a number. It was not, so we fell back to the default port, 443:
https://github.com/googleapis/nodejs-datastore/blob/53e9378f31038b945f996e147db725665f1d12ba/src/index.js
Now that we cache the port as a number, this check will pass, and we will pass along the correct port number to gRPC.

Numberify port from an emulator env var.

---

.circleci/config.yml

Speeding up CI by temporary switching it to non-root user, until GRPC tarball ownership issue is fixed.

Run CI as non-root user

---

package.json
src/index.js
test/index.js

Fixes #27 
When we switched to GAPIC, we put a funnel method in front of all API requests before they were sent to GAPIC. From that, we get the `projectId` from google-auto-auth, to fill in any placeholders. We overlooked a scenario where a projectId is provided by the user already, such as when they are using a local emulator.
After this PR, we will honor that project ID, and not ask google-auto-auth to try to grab it from a credentials file (which is not generally provided when users are working from a local emulator).

Provide user's project ID to google-auto-auth.

---

README.md

The new docs have now been published: https://cloud.google.com/nodejs/docs/reference/datastore/latest/

Revert "fix: Update the link for the Client API Reference"

---

src/entity.js
test/entity.js

Fixes #47. Also corrects some inconsistencies in Key constructor JSDocs.

Don't modify Key constructor input path.

---

.clang-format
.jsdoc.js
README.md
package.json
samples/concepts.js
samples/quickstart.js
samples/system-test/quickstart.test.js
samples/system-test/tasks.test.js
samples/tasks.js
src/entity.ts
src/index.ts
src/query.ts
src/request.ts
src/transaction.ts
src/v1/datastore_client.js
synth.py
system-test/datastore.ts
test/entity.ts
test/gapic-v1.ts
test/index.ts
test/query.ts
test/request.ts
test/transaction.ts
tsconfig.json
tslint.json

*BREAKING CHANGE*: The import style of this library has changed to be consistent with [es modules](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/).
```js
const Datastore = require('@google-cloud/datastore')();
// or...
const Datastore = require('@google-cloud/datastore');
const ds = new Datastore();
```
```js
const {Datastore} = require('@google-cloud/datastore');
const ds = new Datastore();
```

refactor(ts): convert to typescript

---

samples/concepts.js
samples/quickstart.js
samples/tasks.js

Fixes [google-cloud-node/issues/2869](https://github.com/googleapis/google-cloud-node/issues/2869) (it's a good idea to open an issue first for discussion)

refactor(samples): Samples to use async/await

---

samples/concepts.js

When a `get` is returned from datastore the schema of the entity has
been extended to include the key. The comment showing the expected
structure of the entity is being updated to include the key for
completeness.
Fixes b/119342563

Update doc comment showing structure of entity

---

package.json
src/request.ts
src/transaction.ts
system-test/datastore.ts

Fixes #[2883](https://github.com/googleapis/google-cloud-node/issues/2883) partially for nodejs-datastore (it's a good idea to open an issue first for discussion)

refactor: remove async module usage

---

src/entity.ts

Fixes #295
---
It seems like the natural way to see `Key` creation examples is to go to the API docs and click on the `Key` constructor. The `Datastore#key` method is kind of buried and contains more complete examples. This is just a copypasta from the method to the constructor.

docs(key): copy Datastore#key examples to Key ctor

---

src/transaction.ts

fix(types): Make gaxOptions optional in Transaction.rollback()

---

CHANGELOG.md
package.json
samples/package.json

This pull request was generated using releasetool.

Release @google-cloud/datastore v3.1.0

---

CHANGELOG.md
package.json
samples/package.json

This pull request was generated using releasetool.

Release @google-cloud/datastore v3.1.1

---

samples/concepts.js

docs(samples): Update datastore_transaction_retry sample to use function arguments rather than closed variables.

---

package.json
proto/datastore.d.ts

I learned something today!  The `-i` flag on `pbts` will let you specific which imports to explicitly bring in.  Not sure why I need to do this, but 🤷‍♂️   Fixes #345.

fix: make an explicit dependency on long

---

CHANGELOG.md
package.json
samples/package.json

This pull request was generated using releasetool.

Release @google-cloud/datastore v3.1.2

---

src/index.ts
src/query.ts
src/request.ts
src/transaction.ts

fix(docs): move ts overloads above doc string

---

samples/tasks.js

The `id` property of `Key` is a string, update the use site of the key
to parse it as an int when being used to create a key.

fix: add `parseInt` to constructor of task keys

---

src/entity.ts
src/index.ts
system-test/datastore.ts

This prevents `Key path element must not be incomplete` runtime error, and also allows using big int
(datastore.Int) when creating a key using KeyOptions object as an argument.
Fixes #433 (it's a good idea to open an issue first for discussion)

fix: assign more restrictive type to PathType (#433)

---

src/entity.ts
test/entity.ts

Fixes #59 
This exposes a `serialized` property on a Key object. It will correctly differentiate between a key name and id, so that you can re-create a key with it:
```js
const key = datastore.key({
namespace: 'My-NS',
path: ['Company', 123]
);
// Later...
const key = datastore.key(key.serialized);
```

feat: support key re-use from serialized path

---

src/transaction.ts

fix: transaction#run overloads' params types correction

---

src/entity.ts
test/entity.ts

We had issues comparable to #59 in the past. IMO the proposed solution in #474 is only half of the solution: the missing part is more forgiving deserialisation. Note also that users like @beaulac [have reported](https://github.com/googleapis/nodejs-datastore/issues/59#issuecomment-366739401) creating work-arounds for this specifically. This PR solves this by extending the constructor of Key.
Fixes #59. Serialization comes with deserialization, and the current
deserialization did not deal well with plain JavaScript objects like
those returned from JSON deserialization.
Given this implementation is it easy & safe to transfers Keys over
networks and other non-JavaScript interfaces.

feat: support DSInt / DSDouble recognition from JSON

---

package.json

This explicitly upgrades us to `@grpc/grpc-js@0.6.9`, and pins us there, addressing an internal p1 customer issue we are seeing.
We should eventually look at removing this dependency, given that it's already pulled in by `google-gax`, perhaps we could have `google-gax` export the types being used by datastore:
```
import {ChannelCredentials} from '@grpc/grpc-js';
```

fix: upgrade and pin to @grpc/grpc-js@0.6.9

---

.readme-partials.yml
README.md

docs(readme): explain emulator side effects

---

package.json
src/index.ts
src/request.ts
src/transaction.ts
test/index.ts
test/request.ts
test/transaction.ts

BREAKING CHANGE: The `Datastore.projectId` property has been removed, and replaced with an asynchronous `getProjectid()` method.  The projectId cannot be determined synchronously, so the previous approach was to use a `{{projectId}}` string placeholder if the projectId had not yet been acquired.  This made it difficult to know exactly when the property would be defined.  
As an added bonus, the `@google-cloud/projectify` dependency has been removed. Adding @crwilcox because this would be a breaking change (we're about to ship one).

feat: add async getProjectId method
